import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :dobby, DobbyWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Dobby serves one trusted household network over HTTP. A generated
# `force_ssl` redirect would send `dobby.local` and `/mcp` to an HTTPS listener
# the release does not run. TLS belongs at a real reverse proxy if a future
# installation leaves this local-network trust model; it is not simulated here.

# The household reaches Dobby by whatever address it typed — dobby.local, the
# LAN IP the boot log prints, the name a router handed the box — and the
# LiveView socket has to open from all of them. The default check compares the
# browser's Origin with `url[:host]` alone, so a page opened by IP would render
# once and never connect. `:conn` compares Origin with the Host header of the
# request that served the page: whatever address the page came from is the one
# its socket may use, and a page from anywhere else still may not.
config :dobby, DobbyWeb.Endpoint, check_origin: :conn

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
