import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :dobby, DobbyWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Dobby serves one trusted household network over HTTP. A generated
# `force_ssl` redirect would send `dobby.local` and `/mcp` to an HTTPS listener
# the release does not run. TLS belongs at a real reverse proxy if a future
# installation leaves this local-network trust model; it is not simulated here.

# The socket's `check_origin` is set in config/config.exs, not here. This file
# used to set `:conn`, comparing the Origin with the request's own Host, so a
# page opened by IP could still connect. It also let a DNS-rebinding page
# through, since that page's Origin and Host are both the attacker's name.
# `DobbyWeb.Plugs.AllowedHost` now judges both by the house's own names and
# LAN addresses; a name a router hands the box goes in DOBBY_ALLOWED_HOSTS.

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
